### ISSUE TITLE
邊度可以搵倒chars-db.json？

### ISSUE THREAD

**Issue by sora8964** [Saren-Arterius/PyF9#1]
如不方便在這裡回覆，可send E-Mail給我，謝謝。
sora8964@gmail.com

**Comment by Francescaboxw** [comment]
同求chars-db.json.
the links inside app.js seem invalid. Thank you.
francesca@boxw.org

**Comment by Saren-Arterius** [comment]
https://gist.github.com/Saren-Arterius/75cf39a94f6423df1d8045969592b24e
